### PR TITLE
Add variable `hive_config_properties` for custom hive configuration properties

### LINKED ISSUE #90: Unable to drop/rename tables and columns in presto-standalone
## Current behaviour
I miss some parameters in presto that let me drop and rename tables. Current behavior gives me error when trying : `drop table <existing_table>`.

I am not able to add/drop/rename columns either. 

## Suggestion(s)/solution(s) [Optional]
Add the following parameters:
image

The following branch solves this issue: https://github.com/hannemariavister/terraform-nomad-presto/tree/issue_90_add-parameters-to-presto

## Checklist (after created issue)
- [x] Added label(s)
- [ ] Added to project
- [x] Added to milestone

### PR DESCRIPTION
**Pull request by hannemariavister**
## Closes/fixes/resolves issue(s)?
Closes #90 

## What was added/changed/fixed?
Added variable `hive_config_properties` to [variables.tf](https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/master/variables.tf) for custom hive configuration properties. The properties will be appended to `hive.properties` in the respective hcl-file (either [presto.hcl](https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/master/conf/nomad/presto.hcl) or [presto-standalone.hcl](https://github.com/hannemariavister/terraform-nomad-presto/blob/master/conf/nomad/presto_standalone.hcl)).

## Checklist (after created PR)
- [x] Added reviewers
- [x] Added assignee(s)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

### CODE REVIEW

**Comment by claesgill** [comment]
Looks good.

Can you also update the example in the [*Example usage*](https://github.com/fredrikhgrelland/terraform-nomad-presto#example-usage) section?

**Review by zhenik — DISMISSED** [review]
GJ, LGTM

**Comment by pdmthorsrud** [comment]
This looks sweet :D Are these options that should be default? I'm asking since you added them to the example. In that case I think we should keep the feature you just implemented, and move the custom configuration-stuff into the normal configuration

**Comment by hannemariavister** [comment]
> Looks good.
> 
> Can you also update the example in the [_Example usage_](https://github.com/fredrikhgrelland/terraform-nomad-presto#example-usage) section?

Done

**Review by claesgill — APPROVED** [review]
# 🚀

**Review by zhenik — APPROVED** [review]

**Comment by hannemariavister** [comment]
> This looks sweet :D Are these options that should be default? I'm asking since you added them to the example. In that case I think we should keep the feature you just implemented, and move the custom configuration-stuff into the normal configuration

Some of the options that I add to the example is necessary for developing in presto-hive (in most cases). But this solution gives a dynamic and flexible use of this module, and let the users decide which config is necessary in different user-cases. Since this module is an open source product, I think this is a good feature.

**Comment by pdmthorsrud** [comment]
> > This looks sweet :D Are these options that should be default? I'm asking since you added them to the example. In that case I think we should keep the feature you just implemented, and move the custom configuration-stuff into the normal configuration
> 
> Some of the options that I add to the example is necessary for developing in presto-hive (in most cases). But this solution gives a dynamic and flexible use of this module, and let the users decide which config is necessary in different user-cases. Since this module is an open source product, I think this is a good feature.

That's a good point. I concur! Nice job :D

**Review by pdmthorsrud — APPROVED** [review]

**Pull request merged**
