### PR TITLE
Do not restart when certificates are rolled. Presto will reload autom…

### PR DESCRIPTION
**Pull request by fredrikhgrelland**
…atically at 1 min intervals. https://github.com/airlift/airlift/pull/853/files#diff-d044235848e8a9f86952152984072112R327

### CODE REVIEW

**Review by pdmthorsrud — APPROVED** [review]
LGTM, but why did you not remove the certificate-handler when you moved the handling of certificates over to the presto-server?

**Comment by fredrikhgrelland** [comment]
> LGTM, but why did you not remove the certificate-handler when you moved the handling of certificates over to the presto-server?

Uh.. I did?

**Comment by pdmthorsrud** [comment]
> > LGTM, but why did you not remove the certificate-handler when you moved the handling of certificates over to the presto-server?
> 
> Uh.. I did?

You removed the certificate-handler in this PR, but you moved the handling of certificates in #19?

**Comment by fredrikhgrelland** [comment]
True. That is an oversight.

**Pull request merged**
