### PR TITLE
Re-added test & one new

### LINKED ISSUE #81: Readd healthchecks in presto_standalone example
## Current behaviour
No healthchecks

## Expected behaviour
Commented helathchecks should be implemented: https://github.com/fredrikhgrelland/terraform-nomad-presto/blob/master/conf/nomad/presto_standalone.hcl#L50-L67

## How to reproduce?
`make up-standalone`

## Suggestion(s)/solution(s) [Optional]
Maybe add a service proxie to do the checks for us.

## Checklist (after created issue)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

### PR DESCRIPTION
**Pull request by claesgill**
## Closes/fixes/resolves issue(s)?
Closes #81 

## What was added/changed/fixed?
- Re-added test & one new

## Checklist (after created PR)
- [x] Added reviewers
- [x] Added assignee(s)
- [x] Added label(s)
- [x] Added to project
- [x] Added to milestone

### CODE REVIEW

**Review by pdmthorsrud — APPROVED** [review]
LGTM

**Comment by zhenik** [comment]
WDYT to add HTTP request to query health checks are passing as in [the example with minio](https://github.com/fredrikhgrelland/terraform-nomad-minio/blob/master/dev/ansible/03_run_tests.yml#L8-L36)?

**Review by zhenik — DISMISSED** [review]
LGTM

**Review by zhenik — APPROVED** [review]
LGTM

**Review by dangernil — APPROVED** [review]

**Pull request merged**
